### ISSUE TITLE
Registration/Login

### ISSUE THREAD

**Issue by andrewmd5** [derkalle4/gamespy-masterserver#3]
So i've been looking for a catch all game spy alternative ever since being disappointed by "Openspy" not really being open. 

I'm currently in the midst of restoring an older game from 2005, Area 51. Its multiplayer is based around Gamespy.

So the issue I seem to be having is when attempting to register or login, I can see the connection be made to the server from the game, and the server says its sending something, however the game itself disconnects as if it failed to connect at all. So while I might look silly, does this project support login/registration functionality?

**Comment by derkalle4** [comment]
If you would look at my other repositories you would see that there is another project that does the login stuff at all :) - If you wan't to play that game online again it would maybe better to use our hosted version of this masterserver and add pull requests to improve it.

Would be glad to support your game, too. Please write a forum thread on our forum page: https://gameshare.community

More information about GameMaster:
https://gamemaster.gameshare.co

**Comment by andrewmd5** [comment]
Ah! Guess I should have looked, my only issue is I've actually modified the game pretty heavily and have some plans for it that requier me to have access to all the user data, so hosting it myself is the best bet. 

I'll be submitting a few pulls, your login server looks simple enough.

Just for the sake of streamlining things, I would suggest writing a installation guide since this project seems to be in various pieces, so others can setup and host their own master/login servers.

**Comment by derkalle4** [comment]
Didn't have the time to do that. I'm sorry. But If you have a look at these projects it's really simple. Just compile (for the VB things), configure Database and simply run them. I'm interested in how you've modified the game pretty heavily. Maybe I could host neccessary things for you at all? That won't split up the Gamespy community any more ;) because we already have openspy, battlelog.co and other places like tunngle or gameranger to play them online again :)

**Comment by andrewmd5** [comment]
Oh its more than simple for me, I already have the master server running, configuring the login server now, I just meant for people who want to host their own communities.

I've been reverse engineering it for the last months, I fixed the campaign, made it have modern FOV's/resolutions, fixed issues with video playback, nearly have the file format cracked so people can create mods, which will of course mean map creation too, custom sounds, and textures of course.

Since I'm solely focusing on this game, it wouldn't shard anymore of the community, just my own servers so I can control uptime reasonably :package: 

Need access to data so I can control bans, user stats, do integration with various platforms and make a pretty site and help revive the game.

Links of course https://github.com/Codeusa/Area51Patcher

**Comment by derkalle4** [comment]
Sounds great and would be even better If I could support you with my infrastructure :) but feel free to contact me after you've finished your first version for that game and I'll be happy to link to your project to keep players informed about the working games :) - it would also be nice if you could somehow say that you used our source code and include a little back link to https://gameshare.co on your page, too.

**Comment by andrewmd5** [comment]
Of course! I'll just the main menu to list powered by your software instead of gamespy. I'll most likely be rewriting your login server in C#, but the master server will stay the same.

**Comment by derkalle4** [comment]
Would be great if you could upload your login server to github. I'm currently on my way to recreate all our stuff in python and improve it a lot. Public repository will come soon.

**Comment by andrewmd5** [comment]
Open source all the way, when its done I'll push it :)

**Comment by derkalle4** [comment]
Thanks @Codeusa, I think we both understand the importance of open source :) hopefully in future most of the masterserver infrastructures will be open source. I'm on my way to build up a new "gamespy" for new games with other open source masterserver code made by an great guy :)

Btw. thanks for the tweet :)

**Comment by andrewmd5** [comment]
So just wanted to give a quick update, started on a C# rewrite, which is fine, i'm sure i'll get around to finishing it this weekend, however.

Using your login server, I was able to successfully register an account, however it hangs after that in the game, as in the login server doesn't seem to be telling the game the registration was successful, however if I register an account with an already existing profile name, it will give me invalid username/password.

When trying to login, the connection goes to the master server, it says Got avail, says sending too and then I get the message  on the game saying its unable to connect.

Login occurs after registration on Area 51 so it seems that the login portion is failing, registration works fine.

I appreciate any help in getting this fixed so I can move forward.  Am I just setting it up incorrectly?

![](http://i.andrew.im/dnebea.png)

**Comment by andrewmd5** [comment]
And unrelated to the first, since its most likely I'll be using your tech, do you have a preferred logo so I can add it to the main menu and replace all the game spy logos with it

**Comment by derkalle4** [comment]
Hey @Codeusa 

after the registration your client got a response from the server:
`\nur\\userid\1\profileid\1\id\1\final\`
nur = new user registered, more isn't necessary for gamespy games like battlefront / flatout 2. It could be that your game just waiting for some communication with an webserver on port 80, that was the case with borderlands but we've never implemented that. If not, maybe the server wants a more complicated answer request but we've never captured anything like that (but you could have a look at our "stuff" repository from gamespy, there are maybe some hints for login / registration).

Strange that this timeout happened without any further notification. But the timeout did happened somewhere inside of the gpcm.php class file it think :)
Do you have wireshark opened? Can you see if the client is actively sending something after the `\status\1\sesskey\8800\statstring\\locstring\\final\` ?
I don't think he sends anything because otherwise it should get logged first and after that you'll get a disconnect. Maybe the client is closing the socket first?

To help you with your problem: is it enough to download the game and your launcher and hook in the gamespy addresses from my masterserver / loginserver to test that on my own this evening (I'm not at home earlier..)? Or is there something else I need to take care of?

Because of the logo I will create one, soon. Just have an idea and will let you know!

**Comment by andrewmd5** [comment]
@derkalle4 

It should be enough to download the game from my release page and replace all the gamespy addresses (don't run the patcher as that places all the gamespy addresses with openspy).

I wasn't sure what exactly to look for in Wireshark so i dumped my log here for you 

I think the packet you want is number 6771

**Comment by derkalle4** [comment]
Hey @Codeusa 
I had a quick look at your and my own wireshark recording and it seems that this game is missing an connection to the gamespy search manager (port 29901). We never implemented that thing I guess because we didn't have the need for that :/ would be something to figure out. You already know "aluigi"? Was a guy that did a lot of research for Gamespy things. Maybe he has some more interesting information. I'm sorry.

**Comment by andrewmd5** [comment]
So 29901 issue can be mitigated by using code from aluigi off his site, could probably easily be implemented into the main login server, so I'll try doing that later as a pull.

Main issue seems to be with the stat server now, it wasn't properly setup to handle request like authp, getpd, etc so it would time out over and over.

I started on adding them but I'm sure you could probably implement them into your code base faster.

```
 case 'authp':
                            $profile   = explode('\\', $input);
                            $profileId = $profile[4];
                            $response  = gamespy::xor_this("\\pauthr\\$profileId\\lid\\1") . '\final\\';
                            socket_write($this->socket, $response);
                            return true;

                            break;
                        case 'getpd':         
                            $profile   = explode('\\', $input);
                            $profileId = $profile[4];
                            $sid       = $this->session;
                            $response = gamespy::xor_this("\\getpdr\\1\\lid\\1\\pid\\$profileId\\mod\\$profileId\\length\\52\\data\\0000000000000000000000000000000000000000000000000000") . '\final\\';
                            socket_write($this->socket, $response);
                            echo ($profileId);
                            return true;
                            break; 
```

Ihaven't figured out how to get it working exactly though, learning this protocol ever so slowly.

**Comment by Codeusa** [comment]
[registerlogin.zip](https://github.com/derkalle4/gamespy-masterserver/files/120877/registerlogin.zip)
here is a wireshark of a successful register/login over openspy

**Comment by andrewmd5** [comment]
Updated initial post

**Comment by derkalle4** [comment]
Hey @Codeusa 

it's okay if its a simple hack for the php implementation of the login server. I will rewrite all from scratch in python and implement your suggestions there. I think I won't have the time to actually help until the next weekend. But we'll see :)  - if it helps I could try to create some kind of document where I try to explain various functions of the gamespy protocol. Maybe that would make some points clearer for everyone.
It seems that there are other games that using much more things from gamespy then battlefront. Nevermind I don't know if you saw our gamespy client sdk (GameSpyOpenSDKs_v1_00.zip) at the stuff repository? Maybe you can guess more easy all needed functions if you have a look at that :)

**Comment by andrewmd5** [comment]
I look forward to the python rewrite and I can wait until you're less busy next weekend, what I've got hacked together will hold me over long enough to test things :)

**Comment by Codeusa** [comment]
@derkalle4 whenever you get a logo shoot it my way andrew@codeusa523.org

**Comment by derkalle4** [comment]
Hey @Codeusa I think I won't get the python release finished. Our project seems very dead atm. So I use my spare freetime for other development things for now.
